from typing import Any

class Client:
    def __init__(self, *, project: str, location: str) -> None: ...
    @property
    def agent_engines(self) -> Any: ...
    @property
    def evals(self) -> Any: ...
