from typing import Any

class Agent:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def run(self, prompt: str) -> Any: ...

class LocalAgentConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
