"""Pydantic schemas for Antigravity AgentKit declarative configuration."""

from antigravity_agentkit.schema.agent import (
    AgentManifest,
    AgentMetadata,
    AgentProjectData,
    AgentRegistryConfig,
    AgentSpec,
    CapabilitiesConfig,
    CompiledAgentConfig,
    EvalsSpec,
    InstructionsSpec,
    McpAdmissionPolicy,
    McpRegistryConfig,
    McpSpec,
    PoliciesSpec,
    RegistrySkillRef,
    RegistrySpec,
    RuntimeSpec,
    SkillRegistryConfig,
    SkillsSpec,
    SubagentAuth,
    SubagentSpec,
    VertexConfig,
)
from antigravity_agentkit.schema.deployment import (
    DeploymentManifest,
    DeploymentMetadata,
    DeploymentSpec,
    DeployTarget,
    GatewayConfig,
    ResourceLimits,
)
from antigravity_agentkit.schema.evals import (
    EvalCase,
    EvalExpected,
    EvalSuite,
    EvalToolConstraints,
)
from antigravity_agentkit.schema.mcp import McpConfig, McpStdioServerConfig
from antigravity_agentkit.schema.policies import PolicyDocument, PolicyRule, PolicyWhen
from antigravity_agentkit.schema.skills import SkillFrontmatter

__all__ = [
    "AgentManifest",
    "AgentMetadata",
    "AgentProjectData",
    "AgentRegistryConfig",
    "AgentSpec",
    "CapabilitiesConfig",
    "CompiledAgentConfig",
    "DeployTarget",
    "DeploymentManifest",
    "DeploymentMetadata",
    "DeploymentSpec",
    "EvalCase",
    "EvalExpected",
    "EvalSuite",
    "EvalToolConstraints",
    "EvalsSpec",
    "GatewayConfig",
    "InstructionsSpec",
    "McpAdmissionPolicy",
    "McpConfig",
    "McpRegistryConfig",
    "McpSpec",
    "McpStdioServerConfig",
    "PoliciesSpec",
    "PolicyDocument",
    "PolicyRule",
    "PolicyWhen",
    "RegistrySkillRef",
    "RegistrySpec",
    "ResourceLimits",
    "RuntimeSpec",
    "SkillFrontmatter",
    "SkillRegistryConfig",
    "SkillsSpec",
    "SubagentAuth",
    "SubagentSpec",
    "VertexConfig",
]
